apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  name: kube-sa-{{ include "crossplane.fullname" . }}
  {{- include "crossplane.labels" . | nindent 2 }}
spec:
  forProvider:
    name: kube-sa-{{ include "crossplane.fullname" . }}
    {{- include "crossplane.folderid" . | nindent 4 }}
  {{- include "crossplane.deletionPolicy" . | nindent 2 }}
  {{- include "crossplane.provider" . | nindent 2 }}
---
apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  name: alb-sa-{{ include "crossplane.fullname" . }}
  {{- include "crossplane.labels" . | nindent 2 }}
spec:
  forProvider:
    name: alb-sa-{{ include "crossplane.fullname" . }}
    {{- include "crossplane.folderid" . | nindent 4 }}
  {{- include "crossplane.deletionPolicy" . | nindent 2 }}
  {{- include "crossplane.provider" . | nindent 2 }}