{{ if .Values.subnets }}
{{- range $key, $value := .Values.subnets }}
apiVersion: vpc.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Subnet
metadata:
  name: subnet-{{ include "crossplane.fullname" $ }}-{{ $key }}
  {{- include "crossplane.labels" . | nindent 2 }}
spec:
  forProvider:
    name: subnet-{{ include "crossplane.fullname" $ }}-{{ $key }}
    networkIdRef:
      name: vpc-{{ include "crossplane.fullname" $ }}
    v4CidrBlocks:
      - {{ $value.cidr }}
    zone: {{ $value.zone }}
    {{- include "crossplane.folderid" $ | nindent 4 }}
  {{- include "crossplane.deletionPolicy" $ | nindent 2 }}
  {{- include "crossplane.provider" $ | nindent 2 }}
---
{{- end }}
{{ end }}